name: Spelling check

on:
  workflow_dispatch:
  push:
    branches: "*"

jobs:
  spellcheck:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        python -m pip install -U jupyter codespell
    - name: Clean all notebooks
      run: |
        for file in *.ipynb; do echo "${file}"; jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace "${file}"; done
    - name: Check spelling
      run: |
        codespell . --ignore-regex "\b[a-zA-Z]{2,3}\b" -I .dictionary.txt --skip="./.git/*"
